
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fictiondoc_development

test:
  <<: *default
  database: fictiondoc_test
production:
  <<: *default
